### ISSUE TITLE
if two ambiguous keys and one key matches a stage exactly, go with that stage

### ISSUE THREAD

**Issue by peterhurford** [robertzk/stagerunner#48]
For example, if there's a `model` stage and a `model_card` stage, and the user types `run("2.0", "model")` the `model` stage should be run (instead of an error for multiple stages).

**Comment by davluangu** [comment]
@peterhurford your suggestion has been implemented and merged into master

**Comment by peterhurford** [comment]
:+1:

**Comment by davluangu** [comment]
@robertzk, i think you need to `git tag 0.5.2`

**Comment by robertzk** [comment]
Oops, don

On Mon, Oct 19, 2015 at 11:15 AM, David Nguyen <notifications@github.com>
wrote:

> @robertzk <https://github.com/robertzk>, i think you need to git tag 0.5.2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robertzk/stagerunner/issues/48#issuecomment-149262985>
> .
>



-- 
-Robert Krzyzanowski
